const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('quackers', {
  setInteractive: (interactive) => ipcRenderer.send('set-interactive', interactive),
  hideNow: () => ipcRenderer.send('hide-now'),
  quit: () => ipcRenderer.send('quit'),
  openKeyWindow: () => ipcRenderer.send('open-key-window'),
  impulseShown: (kind, dreamId = null) => ipcRenderer.send('impulse-shown', { kind, dreamId }),
  onboardComplete: (skin, duckName, personName) =>
    ipcRenderer.send('onboard-complete', { skin, duckName, personName }),
  onEggDrop: (cb) => ipcRenderer.on('quackers:egg-drop', cb),
  onGround: (cb) => ipcRenderer.on('quackers:ground', (_e, offset) => cb(offset)),
  onTrick: (cb) => ipcRenderer.on('quackers:trick', (_e, data) => cb(data)),
  onTrickEvent: (cb) => ipcRenderer.on('quackers:trick-event', (_e, data) => cb(data)),
  trickTeachStart: (name) => ipcRenderer.invoke('trick-teach-start', name),
  trickTeachFinish: (narration) => ipcRenderer.invoke('trick-teach-finish', narration),
  trickPerform: (name, guidance) => ipcRenderer.invoke('trick-perform', { name, guidance }),
  trickConfirm: (approved) => ipcRenderer.invoke('trick-confirm', approved),
  trickCancel: () => ipcRenderer.invoke('trick-cancel'),
  workshopCheck: (name) => ipcRenderer.invoke('workshop-check', name),
  workshopBuild: (req) => ipcRenderer.invoke('workshop-build', req),
  workshopRun: (name) => ipcRenderer.invoke('workshop-run', name),
  workshopClose: () => ipcRenderer.invoke('workshop-close'),
  workshopEquip: (name) => ipcRenderer.invoke('workshop-equip', name),
  workshopUnequip: (name) => ipcRenderer.invoke('workshop-unequip', name),
  workshopState: (id, state) => ipcRenderer.send('workshop-state', { id, state }),
  workshopSmokeResult: (token, ok, error) => ipcRenderer.send('workshop-smoke-result', { token, ok, error }),
  propsGet: () => ipcRenderer.invoke('props-get'),
  onWorkshop: (cb) => ipcRenderer.on('quackers:workshop', (_e, data) => cb(data)),
  onWorkshopEvent: (cb) => ipcRenderer.on('quackers:workshop-event', (_e, data) => cb(data)),
  onWorkshopSmoke: (cb) => ipcRenderer.on('quackers:workshop-smoke', (_e, data) => cb(data)),
  onStageOpen: (cb) => ipcRenderer.on('quackers:stage-open', (_e, data) => cb(data)),
  onStageClose: (cb) => ipcRenderer.on('quackers:stage-close', cb),
  onProps: (cb) => ipcRenderer.on('quackers:props', (_e, data) => cb(data)),
  onDismiss: (cb) => ipcRenderer.on('quackers:dismiss', cb),
  onArrive: (cb) => ipcRenderer.on('quackers:arrive', cb),
  onTalkToggle: (cb) => ipcRenderer.on('quackers:talk-toggle', cb),
  onDigested: (cb) => ipcRenderer.on('quackers:digested', cb),
  onDreaming: (cb) => ipcRenderer.on('quackers:dreaming', (_e, on) => cb(on)),
  onDreamed: (cb) => ipcRenderer.on('quackers:dreamed', (_e, data) => cb(data || {})),
  onImpulse: (cb) => ipcRenderer.on('quackers:impulse', (_e, data) => cb(data)),
  onBuddy: (cb) => ipcRenderer.on('quackers:buddy', (_e, data) => cb(data)),
  onDnd: (cb) => ipcRenderer.on('quackers:dnd', (_e, on) => cb(on)),
  onCall: (cb) => ipcRenderer.on('quackers:call', (_e, on) => cb(on)),
  onMusic: (cb) => ipcRenderer.on('quackers:music', (_e, music) => cb(music)),
  onUserAway: (cb) => ipcRenderer.on('quackers:user-away', cb),
  onUserBack: (cb) => ipcRenderer.on('quackers:user-back', cb),
  onLooking: (cb) => ipcRenderer.on('quackers:looking', cb),
  onLookingDone: (cb) => ipcRenderer.on('quackers:looking-done', cb),
  onClipRequest: (cb) => ipcRenderer.on('quackers:clip-request', cb),
  onVoiceGranted: (cb) => ipcRenderer.on('quackers:voice-granted', cb),
  realtimeConnect: (arg) => ipcRenderer.invoke('realtime-connect', arg),
  realtimePrewarm: () => ipcRenderer.invoke('realtime-prewarm'),
  chatOpen: () => ipcRenderer.invoke('chat-open'),
  chatSend: (text) => ipcRenderer.invoke('chat-send', text),
  chatClose: () => ipcRenderer.invoke('chat-close'),
  onChatDelta: (cb) => ipcRenderer.on('quackers:chat-delta', (_e, d) => cb(d)),
  onChatTurnEnd: (cb) => ipcRenderer.on('quackers:chat-turn-end', (_e, text) => cb(text)),
  onChatTyping: (cb) => ipcRenderer.on('quackers:chat-typing', (_e, on) => cb(on)),
  onChatEmote: (cb) => ipcRenderer.on('quackers:chat-emote', (_e, emotion) => cb(emotion)),
  onChatLooking: (cb) => ipcRenderer.on('quackers:chat-looking', (_e, on) => cb(on)),
  onChatIdle: (cb) => ipcRenderer.on('quackers:chat-idle', cb),
  onChatClose: (cb) => ipcRenderer.on('quackers:chat-close', cb),
  onChatSwitchVoice: (cb) => ipcRenderer.on('quackers:chat-switch-voice', cb),
  onChatRequest: (cb) => ipcRenderer.on('quackers:chat-request', cb),
  captureScreen: () => ipcRenderer.invoke('capture-screen'),
  captureApp: (appName) => ipcRenderer.invoke('capture-app', appName),
  recall: (query) => ipcRenderer.invoke('recall', query),
  thinkHard: (payload) => ipcRenderer.invoke('think-hard', payload),
  memoryAdd: (note) => ipcRenderer.invoke('memory-add', note),
  dreamResearchQueue: (request) => ipcRenderer.invoke('dream-research-queue', request),
  dreamOfferTake: (prompted) => ipcRenderer.invoke('dream-offer-take', Boolean(prompted)),
  dreamSettingsGet: () => ipcRenderer.invoke('dream-settings-get'),
  dreamSettingsSet: (settings) => ipcRenderer.invoke('dream-settings-set', settings),
  dreamSourceOpen: (url) => ipcRenderer.invoke('dream-source-open', url),
  scrapbookAdd: (entry) => ipcRenderer.invoke('scrapbook-add', entry),
  scrapbookList: () => ipcRenderer.invoke('scrapbook-list'),
  scrapbookPin: (id, pinned) => ipcRenderer.invoke('scrapbook-pin', { id, pinned }),
  scrapbookDelete: (id) => ipcRenderer.invoke('scrapbook-delete', id),
  scrapbookOpenAsset: (id) => ipcRenderer.invoke('scrapbook-open-asset', id),
  reminderAdd: (reminder) => ipcRenderer.invoke('reminder-add', reminder),
  reminderList: (includeDone = false) => ipcRenderer.invoke('reminder-list', includeDone),
  reminderGet: (id) => ipcRenderer.invoke('reminder-get', id),
  reminderShow: (id) => ipcRenderer.invoke('reminder-show', id),
  reminderDone: (id) => ipcRenderer.invoke('reminder-done', id),
  reminderSnooze: (id, minutes) => ipcRenderer.invoke('reminder-snooze', { id, minutes }),
  reminderDismiss: (id) => ipcRenderer.invoke('reminder-dismiss', id),
  reminderDelete: (id) => ipcRenderer.invoke('reminder-delete', id),
  onRemindersChanged: (cb) => ipcRenderer.on('quackers:reminders-changed', cb),
  onStickyDelivery: (cb) => ipcRenderer.on('quackers:sticky-delivery', (_event, data) => cb(data)),
  stickyDeliveryReady: (id) => ipcRenderer.send('sticky-delivery-ready', id),
  workGuardGet: () => ipcRenderer.invoke('work-guard-get'),
  workGuardSet: (settings) => ipcRenderer.invoke('work-guard-set', settings),
  workGuardClear: () => ipcRenderer.invoke('work-guard-clear'),
  computerAction: (action) => ipcRenderer.invoke('computer-action', action),
  integrationStatus: () => ipcRenderer.invoke('integration-status'),
  integrationInstall: (kind) => ipcRenderer.invoke('integration-install', kind),
  integrationRemove: (kind) => ipcRenderer.invoke('integration-remove', kind),
  rememberName: (name) => ipcRenderer.invoke('remember-name', name),
  gameResult: (game, winner) => ipcRenderer.invoke('game-result', { game, winner }),
  stageGet: () => ipcRenderer.invoke('stage-get'),
  hatch: () => ipcRenderer.invoke('hatch'),
  keyStatus: () => ipcRenderer.invoke('key-status'),
  keySave: (key) => ipcRenderer.invoke('key-save', key),
  clipSave: (arrayBuffer) => ipcRenderer.invoke('clip-save', arrayBuffer),
  digestTranscript: (lines) => ipcRenderer.send('digest-transcript', lines),
  happening: (type, detail) => ipcRenderer.send('happening', { type, detail }),
  logEvent: (type, data) => ipcRenderer.send('log-event', { type, data }),
  spineGet: () => ipcRenderer.invoke('spine-get'),
  spineDelete: (type, id) => ipcRenderer.invoke('spine-delete', { type, id }),
  spineEdit: (id, statement) => ipcRenderer.invoke('spine-edit', { id, statement }),
});
